BEGIN TRANSACTION;
INSERT INTO "seeds" VALUES (1,'娱乐','https://www.toutiao.com/api/pc/feed/?category=news_entertainment&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (2,'科技','https://www.toutiao.com/api/pc/feed/?category=news_tech&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (3,'游戏','https://www.toutiao.com/api/pc/feed/?category=news_game&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (4,'体育','https://www.toutiao.com/api/pc/feed/?category=news_sports&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (5,'汽车','https://www.toutiao.com/api/pc/feed/?category=news_car&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (6,'财经','https://www.toutiao.com/api/pc/feed/?category=news_finance&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (7,'军事','https://www.toutiao.com/api/pc/feed/?category=news_military&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (8,'国际','https://www.toutiao.com/api/pc/feed/?category=news_world&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (9,'时尚','https://www.toutiao.com/api/pc/feed/?category=news_fashion&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (10,'旅游','https://www.toutiao.com/api/pc/feed/?category=news_travel&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (11,'探索','https://www.toutiao.com/api/pc/feed/?category=news_discovery&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (12,'育儿','https://www.toutiao.com/api/pc/feed/?category=news_baby&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (13,'养生','https://www.toutiao.com/api/pc/feed/?category=news_regimen&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (14,'美文','https://www.toutiao.com/api/pc/feed/?category=news_essay&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (15,'历史','https://www.toutiao.com/api/pc/feed/?category=news_history&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (16,'美食','https://www.toutiao.com/api/pc/feed/?category=news_food&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
INSERT INTO "seeds" VALUES (17,'all','https://www.toutiao.com/api/pc/feed/?min_behot_time=0&category=__all__&utm_source=toutiao');
INSERT INTO "seeds" VALUES (18,'时政','https://www.toutiao.com/api/pc/feed/?category=news_politics&utm_source=toutiao&max_behot_time=0&max_behot_time_tmp=0');
COMMIT;
